import React from 'react';
import { Bot, Layers, Info } from 'lucide-react';

const About: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      
      {/* About Section */}
      <section className="mb-16">
        <h1 className="text-4xl font-serif font-bold text-white mb-6">About Aether Art</h1>
        <div className="prose prose-invert max-w-none text-gray-300 leading-relaxed">
          <p className="mb-4">
            Aether Art is a demonstration of the next generation of creative tools, powered by Google's Gemini API. 
            We believe in democratizing art creation, allowing anyone with an idea to visualize it instantly.
          </p>
          <p>
            Our platform leverages advanced diffusion models and Large Language Models (LLMs) to understand the nuance of human language 
            and translate it into pixel-perfect imagery. Whether you are a concept artist, a hobbyist, or someone looking for inspiration, 
            Aether provides the canvas for your imagination.
          </p>
        </div>
      </section>

      {/* Technology */}
      <section className="mb-16 grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-gray-800 p-6 rounded-xl border border-gray-700">
          <div className="flex items-center gap-3 mb-4 text-indigo-400">
            <Bot size={24} />
            <h3 className="text-xl font-bold text-white">The AI Model</h3>
          </div>
          <p className="text-gray-400 text-sm">
            We utilize the <strong>gemini-2.5-flash-image</strong> model. It is optimized for speed and fidelity, capable of understanding complex prompts including lighting, artistic styles, and composition instructions.
          </p>
        </div>
        <div className="bg-gray-800 p-6 rounded-xl border border-gray-700">
          <div className="flex items-center gap-3 mb-4 text-purple-400">
            <Layers size={24} />
            <h3 className="text-xl font-bold text-white">Tech Stack</h3>
          </div>
          <p className="text-gray-400 text-sm">
            Built with React 18, TypeScript, and Tailwind CSS. The application is a Single Page Application (SPA) designed for performance and responsiveness.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mb-16">
        <h2 className="text-3xl font-bold text-white mb-8 flex items-center gap-3">
          <Info className="text-gray-500" /> Frequently Asked Questions
        </h2>
        
        <div className="space-y-4">
          <details className="group bg-gray-800 rounded-lg p-4 border border-gray-700 cursor-pointer">
            <summary className="flex justify-between items-center font-medium text-white list-none">
              <span>Is this service free?</span>
              <span className="transition group-open:rotate-180">
                <svg fill="none" height="24" shapeRendering="geometricPrecision" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" viewBox="0 0 24 24" width="24"><path d="M6 9l6 6 6-6"></path></svg>
              </span>
            </summary>
            <p className="text-gray-400 mt-3 text-sm">
              Currently, this is a demonstration app. Access depends on the configured API quota of the hosting provider.
            </p>
          </details>

          <details className="group bg-gray-800 rounded-lg p-4 border border-gray-700 cursor-pointer">
            <summary className="flex justify-between items-center font-medium text-white list-none">
              <span>Who owns the copyright?</span>
              <span className="transition group-open:rotate-180">
                <svg fill="none" height="24" shapeRendering="geometricPrecision" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" viewBox="0 0 24 24" width="24"><path d="M6 9l6 6 6-6"></path></svg>
              </span>
            </summary>
            <p className="text-gray-400 mt-3 text-sm">
              Images generated by AI are generally considered public domain or owned by the creator depending on local laws. We do not claim ownership of your creations.
            </p>
          </details>

          <details className="group bg-gray-800 rounded-lg p-4 border border-gray-700 cursor-pointer">
            <summary className="flex justify-between items-center font-medium text-white list-none">
              <span>Are there safety filters?</span>
              <span className="transition group-open:rotate-180">
                <svg fill="none" height="24" shapeRendering="geometricPrecision" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" viewBox="0 0 24 24" width="24"><path d="M6 9l6 6 6-6"></path></svg>
              </span>
            </summary>
            <p className="text-gray-400 mt-3 text-sm">
              Yes. The Gemini API includes robust safety filters to prevent the generation of harmful, explicit, or hateful content.
            </p>
          </details>
        </div>
      </section>

      {/* Contact */}
      <section>
        <h2 className="text-2xl font-bold text-white mb-6">Contact Us</h2>
        <div className="bg-gray-800 p-8 rounded-2xl border border-gray-700">
          <form className="space-y-4" onSubmit={(e) => e.preventDefault()}>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
               <div>
                 <label className="block text-sm text-gray-400 mb-1">Name</label>
                 <input type="text" className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2 text-white" />
               </div>
               <div>
                 <label className="block text-sm text-gray-400 mb-1">Email</label>
                 <input type="email" className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2 text-white" />
               </div>
             </div>
             <div>
                <label className="block text-sm text-gray-400 mb-1">Message</label>
                <textarea rows={4} className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2 text-white"></textarea>
             </div>
             <button className="bg-primary hover:bg-indigo-600 text-white px-6 py-2 rounded-lg font-medium transition-colors">
               Send Message
             </button>
          </form>
        </div>
      </section>

    </div>
  );
};

export default About;
